Update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -60,11 +60,16 @@ services:
     volumes:
       - ./migrations:/app/migration 
     command:
-      - "-path"
-      - "/migration"
-      - "-database"
-      - "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-autosphere}?sslmode=disable"  
-      - "up"
+      - /bin/sh
+      - "-c"
+      - |
+        if ! command -v migrate &> /dev/null; then
+          echo "❌ migrate CLI not found!"
+          exit 1
+        fi
+        echo "✅ migrate CLI found!"
+        migrate -path /migration -database "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-autosphere}?sslmode=disable" up;
+        tail -f /dev/null
     depends_on:
       - postgres 
     restart: on-failure  
